version: '3.8'
services:
  mongo:
    image: mongo:5.0-focal
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - api_net

  api:
    build:
      dockerfile: build/Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - api_net
    env_file:
      - .env

networks:
  api_net:
    driver: bridge
